apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: 543816070942.dkr.ecr.ap-south-1.amazonaws.com/movieapp-backend
        command: ["php", "artisan", "migrate", "--force"]
        env: [same as deployment]
      restartPolicy: OnFailure
      backoffLimit: 4