apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  host: <base64-encoded RDS_ENDPOINT>
  database: <base64-encoded movie-app-db>
  username: <base64-encoded admin>
  password: <base64-encoded Movieapp2025>