apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  host: bW92aWUtYXBwLWRiLmNsYmRqNDR2N2M0eC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20= #base64 encoded
  database: bW92aWUtYXBwLWRi
  username: YWRtaW4=
  password: TW92aWVhcHAyMDI1